### ISSUE TITLE
Support for searching path for sourcekit-lsp 

### ISSUE THREAD

**Issue by notpeter** [zed-extensions/swift#10]
See: https://github.com/zed-industries/zed/issues/13302

User (@teampuzel) fixed it by modifying source:
```
if let Some(path) = worktree.which("sourcekit-lsp") {
    return Ok(zed::Command {
        command: path,
        args: Default::default(),
        env: worktree.shell_env(),
    });
}
```

**Comment by Zollerboy1** [comment]
I would recommend waiting until version 0.0.7 of `zed_extension_api` (which hopefully isn't too far off in the future) is published because then we could do something along these lines:

```rs
let settings = LspSettings::for_worktree("sourcekit-lsp", worktree)?;

let command = match settings.binary {
    Some(BinarySettings {
        path,
        arguments,
        path_lookup,
    }) => {
        let (path, env) = match (path, path_lookup) {
            (Some(path), _) => (Some(path.into()), None),
            (None, Some(true)) => {
                let path = worktree.which("sourcekit-lsp");
                let env = worktree.shell_env();
                (path, Some(env))
            }
            (None, Some(false)) | (None, None) => (None, None),
        };
        path.map(|command| zed::Command {
            command,
            args: arguments
                .unwrap_or_default()
                .iter()
                .map(|arg| arg.into())
                .collect(),
            env,
        })
    }
    _ => None,
};

Ok(command.unwrap_or_else(|| zed::Command {
    command: "/usr/bin/xcrun".into(),
    args: vec!["sourcekit-lsp".into()],
    env: Default::default(),
}))
```

IIUIC, this should allow users to configure the language server binary similar to how it can be done for C, Rust, and Go like so:

```json
{
  "lsp": {
    "sourcekit-lsp": {
      "binary": {
        "path_lookup": true
      }
    }
  }
}
```

or

```json
{
  "lsp": {
    "sourcekit-lsp": {
      "binary": {
        "path": "/path/to/sourcekit-lsp",
        "arguments": []
      }
    }
  }
}
```

**Comment by maxdeviant** [comment]
> I would recommend waiting until version 0.0.7 of `zed_extension_api` is published (which hopefully isn't too far off in the future) because then we could do something along these lines:

Which part of this is dependent on v0.0.7 of the extension API?

It looks like all of this can be done with v0.0.6.

**Comment by Zollerboy1** [comment]
> Which part of this is dependent on v0.0.7 of the extension API?
>
> It looks like all of this can be done with v0.0.6.

You're partially right, but I've just noticed that my complete approach actually doesn't even work in v0.0.7 either, as the `BinarySettings` struct still doesn't have the `path_lookup` field:

https://github.com/zed-industries/zed/blob/492040dec4e0df70c912894db4bdb7864508c995/crates/extension_api/wit/since_v0.0.7/settings.rs#L24-L29

Somehow I looked that up wrong when researching how this is handled for Rust & co (which doesnÄt need the extension API).

So maybe we should push for parity between `extension_api::wit::settings::BinarySettings` and `project::project_settings::BinarySettings` so that my approach actually works with v0.0.7.

**Comment by maxdeviant** [comment]
Would it work to find the language server binary on the $PATH? That's how our other extensions work.

**Comment by Zollerboy1** [comment]
Sure, that would work. I just thought that it would be nice if the config for Swift (and maybe down the road for the other languages in extensions as well) worked like it does for the natively supported languages (currently that's Rust, C, and Go, I think).

**Comment by maxdeviant** [comment]
We now check for `sourcekit-lsp` on the $PATH in #11.
